In [1]:
import numpy as np
import pandas as pd
import glob
import matplotlib.pyplot as plt

In [2]:
training = pd.read_csv("~/GIT/Research_PatrickP/periodic_2d_disads_2d/res/data1.txt", sep=' ', header=0)
training 
#wrong header

          #    time  covered_sites_spec1  covered_sites_spec2
0      0.01   354.0                340.0                  NaN
1      0.02   646.0                644.0                  NaN
2      0.03   882.0                886.0                  NaN
3      0.04  1080.0               1116.0                  NaN
4      0.05  1266.0               1284.0                  NaN
...     ...     ...                  ...                  ...
1995  19.96  2370.0               2354.0                  NaN
1996  19.97  2360.0               2344.0                  NaN
1997  19.98  2320.0               2342.0                  NaN
1998  19.99  2312.0               2330.0                  NaN
1999  20.00  2308.0               2336.0                  NaN

[2000 rows x 4 columns]

In [3]:
list(training.columns.values)

['#', 'time', 'covered_sites_spec1', 'covered_sites_spec2']

In [4]:
training=training.rename(columns={'#': 'time','time':'covered_sites_spec1','covered_sites_spec1':'covered_sites_spec2','covered_sites_spec2':'coverage_spec1'})

In [5]:
training

       time  covered_sites_spec1  covered_sites_spec2  coverage_spec1
0      0.01                354.0                340.0             NaN
1      0.02                646.0                644.0             NaN
2      0.03                882.0                886.0             NaN
3      0.04               1080.0               1116.0             NaN
4      0.05               1266.0               1284.0             NaN
...     ...                  ...                  ...             ...
1995  19.96               2370.0               2354.0             NaN
1996  19.97               2360.0               2344.0             NaN
1997  19.98               2320.0               2342.0             NaN
1998  19.99               2312.0               2330.0             NaN
1999  20.00               2308.0               2336.0             NaN

[2000 rows x 4 columns]

In [6]:
training['coverage_spec1']=training['covered_sites_spec1'].apply(lambda x: x/10000.0)
training.insert(4,'coverage_spec2',training['covered_sites_spec2'].apply(lambda x: x/10000.0),True)
# training['coverage_spec2']=training['covered_sites_spec2'].apply(lambda x: x/10000.0)

In [7]:
training

,time,covered_sites_spec1,covered_sites_spec2,coverage_spec1,coverage_spec2
0,0.01,354.0,340.0,0.0354,0.0340
1,0.02,646.0,644.0,0.0646,0.0644
2,0.03,882.0,886.0,0.0882,0.0886
3,0.04,1080.0,1116.0,0.1080,0.1116
4,0.05,1266.0,1284.0,0.1266,0.1284
...,...,...,...,...,...
1995,19.96,2370.0,2354.0,0.2370,0.2354
1996,19.97,2360.0,2344.0,0.2360,0.2344
1997,19.98,2320.0,2342.0,0.2320,0.2342
1998,19.99,2312.0,2330.0,0.2312,0.2330
1999,20.00,2308.0,2336.0,0.2308,0.2336

In [8]:
import os
path = os.path.expanduser('~/GIT/Research_PatrickP/periodic_2d_disads_2d/res/')
text_files = [f for f in os.listdir(path) if f.endswith('.txt')]
text_files

['data1.txt',
 'data2.txt',
 'data3.txt',
 'data4.txt',
 'data5.txt',
 'data6.txt',
 'data7.txt',
 'data8.txt',
 'data9.txt',
 'data10.txt',
 'data11.txt',
 'data12.txt',
 'data13.txt',
 'data14.txt',
 'data15.txt',
 'data16.txt',
 'data17.txt',
 'data18.txt',
 'data19.txt',
 'data20.txt',
 'data21.txt',
 'data22.txt',
 'data23.txt',
 'data24.txt',
 'data25.txt',
 'data26.txt',
 'data27.txt',
 'data28.txt',
 'data29.txt',
 'data30.txt',
 'data31.txt',
 'data32.txt',
 'data33.txt',
 'data34.txt',
 'data35.txt',
 'data36.txt',
 'data37.txt',
 'data38.txt',
 'data39.txt',
 'data40.txt',
 'data41.txt',
 'data42.txt',
 'data43.txt',
 'data44.txt',
 'data45.txt',
 'data46.txt',
 'data47.txt',
 'data48.txt',
 'data49.txt',
 'data50.txt',
 'data51.txt',
 'data52.txt',
 'data53.txt',
 'data54.txt',
 'data55.txt',
 'data56.txt',
 'data57.txt',
 'data58.txt',
 'data59.txt',
 'data60.txt',
 'data61.txt',
 'data62.txt',
 'data63.txt',
 'data64.txt',
 'data65.txt',
 'data66.txt',
 'data67.txt',
 'data68.txt',
 'data69.txt',
 'data70.txt',
 'data71.txt',
 'data72.txt',
 'data73.txt',
 'data74.txt',
 'data75.txt',
 'data76.txt',
 'data77.txt',
 'data78.txt',
 'data79.txt',
 'data80.txt',
 'data81.txt',
 'data82.txt',
 'data83.txt',
 'data84.txt',
 'data85.txt',
 'data86.txt',
 'data87.txt',
 'data88.txt',
 'data89.txt',
 'data90.txt',
 'data91.txt',
 'data92.txt',
 'data93.txt',
 'data94.txt',
 'data95.txt',
 'data96.txt',
 'data97.txt',
 'data98.txt',
 'data99.txt',
 'data100.txt',
 'data101.txt',
 'data102.txt',
 'data103.txt',
 'data104.txt',
 'data105.txt',
 'data106.txt',
 'data107.txt',
 'data108.txt',
 'data109.txt',
 'data110.txt',
 'data111.txt',
 'data112.txt',
 'data113.txt',
 'data114.txt',
 'data115.txt',
 'data116.txt',
 'data117.txt',
 'data118.txt',
 'data119.txt',
 'data120.txt',
 'data121.txt',
 'data122.txt',
 'data123.txt',
 'data124.txt',
 'data125.txt',
 'data126.txt',
 'data127.txt',
 'data128.txt',
 'data129.txt',
 'data130.txt',
 'data131.txt',
 'data132.txt',
 'data133.txt',
 'data134.txt',
 'data135.txt',
 'data136.txt',
 'data137.txt',
 'data138.txt',
 'data139.txt',
 'data140.txt',
 'data141.txt',
 'data142.txt',
 'data143.txt',
 'data144.txt',
 'data145.txt',
 'data146.txt',
 'data147.txt',
 'data148.txt',
 'data149.txt',
 'data150.txt',
 'data151.txt',
 'data152.txt',
 'data153.txt',
 'data154.txt',
 'data155.txt',
 'data156.txt',
 'data157.txt',
 'data158.txt',
 'data159.txt',
 'data160.txt',
 'data161.txt',
 'data162.txt',
 'data163.txt',
 'data164.txt',
 'data165.txt',
 'data166.txt',
 'data167.txt',
 'data168.txt',
 'data169.txt',
 'data170.txt',
 'data171.txt',
 'data172.txt',
 'data173.txt',
 'data174.txt',
 'data175.txt',
 'data176.txt',
 'data177.txt',
 'data178.txt',
 'data179.txt',
 'data180.txt',
 'data181.txt',
 'data182.txt',
 'data183.txt',
 'data184.txt',
 'data185.txt',
 'data186.txt',
 'data187.txt',
 'data188.txt',
 'data189.txt',
 'data190.txt',
 'data191.txt',
 'data192.txt',
 'data193.txt',
 'data194.txt',
 'data195.txt',
 'data196.txt',
 'data197.txt',
 'data198.txt',
 'data199.txt',
 'data200.txt',
 'data201.txt',
 'data202.txt',
 'data203.txt',
 'data204.txt',
 'data205.txt',
 'data206.txt',
 'data207.txt',
 'data208.txt',
 'data209.txt',
 'data210.txt',
 'data211.txt',
 'data212.txt',
 'data213.txt',
 'data214.txt',
 'data215.txt',
 'data216.txt',
 'data217.txt',
 'data218.txt',
 'data219.txt',
 'data220.txt',
 'data221.txt',
 'data222.txt',
 'data223.txt',
 'data224.txt',
 'data225.txt',
 'data226.txt',
 'data227.txt',
 'data228.txt',
 'data229.txt',
 'data230.txt',
 'data231.txt',
 'data232.txt',
 'data233.txt',
 'data234.txt',
 'data235.txt',
 'data236.txt',
 'data237.txt',
 'data238.txt',
 'data239.txt',
 'data240.txt',
 'data241.txt',
 'data242.txt',
 'data243.txt',
 'data244.txt',
 'data245.txt',
 'data246.txt',
 'data247.txt',
 'data248.txt',
 'data249.txt',
 'data250.txt',
 'data251.txt',
 'data252.txt',
 'data253.txt',
 'data254.txt',
 'data255.txt',
 'data256.txt',
 'data257.txt',
 'data258.txt',
 'data259.txt',
 'data260.txt',
 'data261.txt',
 'data262.txt',
 'data263.txt',
 'data264.txt',
 'data265.txt',
 'data266.txt',
 'data267.txt',
 'data268.txt',
 'data269.txt',
 'data270.txt',
 'data271.txt',
 'data272.txt',
 'data273.txt',
 'data274.txt',
 'data275.txt',
 'data276.txt',
 'data277.txt',
 'data278.txt',
 'data279.txt',
 'data280.txt',
 'data281.txt',
 'data282.txt',
 'data283.txt',
 'data284.txt',
 'data285.txt',
 'data286.txt',
 'data287.txt',
 'data288.txt',
 'data289.txt',
 'data290.txt',
 'data291.txt',
 'data292.txt',
 'data293.txt',
 'data294.txt',
 'data295.txt',
 'data296.txt',
 'data297.txt',
 'data298.txt',
 'data299.txt',
 'data300.txt',
 'data301.txt',
 'data302.txt',
 'data303.txt',
 'data304.txt',
 'data305.txt',
 'data306.txt',
 'data307.txt',
 'data308.txt',
 'data309.txt',
 'data310.txt',
 'data311.txt',
 'data312.txt',
 'data313.txt',
 'data314.txt',
 'data315.txt',
 'data316.txt',
 'data317.txt',
 'data318.txt',
 'data319.txt',
 'data320.txt',
 'data321.txt',
 'data322.txt',
 'data323.txt',
 'data324.txt',
 'data325.txt',
 'data326.txt',
 'data327.txt',
 'data328.txt',
 'data329.txt',
 'data330.txt',
 'data331.txt',
 'data332.txt',
 'data333.txt',
 'data334.txt',
 'data335.txt',
 'data336.txt',
 'data337.txt',
 'data338.txt',
 'data339.txt',
 'data340.txt',
 'data341.txt',
 'data342.txt',
 'data343.txt',
 'data344.txt',
 'data345.txt',
 'data346.txt',
 'data347.txt',
 'data348.txt',
 'data349.txt',
 'data350.txt',
 'data351.txt',
 'data352.txt',
 'data353.txt',
 'data354.txt',
 'data355.txt',
 'data356.txt',
 'data357.txt',
 'data358.txt',
 'data359.txt',
 'data360.txt',
 'data361.txt',
 'data362.txt',
 'data363.txt',
 'data364.txt',
 'data365.txt',
 'data366.txt',
 'data367.txt',
 'data368.txt',
 'data369.txt',
 'data370.txt',
 'data371.txt',
 'data372.txt',
 'data373.txt',
 'data374.txt',
 'data375.txt',
 'data376.txt',
 'data377.txt',
 'data378.txt',
 'data379.txt',
 'data380.txt',
 'data381.txt',
 'data382.txt',
 'data383.txt',
 'data384.txt',
 'data385.txt',
 'data386.txt',
 'data387.txt',
 'data388.txt',
 'data389.txt',
 'data390.txt',
 'data391.txt',
 'data392.txt',
 'data393.txt',
 'data394.txt',
 'data395.txt',
 'data396.txt',
 'data397.txt',
 'data398.txt',
 'data399.txt',
 'data400.txt']

In [9]:
path ='~/GIT/Research_PatrickP/periodic_2d_disads_2d/res/'
# filenames = glob.glob(path + "/*.txt")
# creating empty list
dataFrames = list()
# iterating through CSV file in current directory
for text_file in text_files:
    dataFrames.append(pd.read_csv(path+text_file, header=0, sep=' '))
    print(text_file)

data1.txt
data2.txt
data3.txt
data4.txt
data5.txt
data6.txt
data7.txt
data8.txt
data9.txt
data10.txt
data11.txt
data12.txt
data13.txt
data14.txt
data15.txt
data16.txt
data17.txt
data18.txt
data19.txt
data20.txt
data21.txt
data22.txt
data23.txt
data24.txt
data25.txt
data26.txt
data27.txt
data28.txt
data29.txt
data30.txt
data31.txt
data32.txt
data33.txt
data34.txt
data35.txt
data36.txt
data37.txt
data38.txt
data39.txt
data40.txt
data41.txt
data42.txt
data43.txt
data44.txt
data45.txt
data46.txt
data47.txt
data48.txt
data49.txt
data50.txt
data51.txt
data52.txt
data53.txt
data54.txt
data55.txt
data56.txt
data57.txt
data58.txt
data59.txt
data60.txt
data61.txt
data62.txt
data63.txt
data64.txt
data65.txt
data66.txt
data67.txt
data68.txt
data69.txt
data70.txt
data71.txt
data72.txt
data73.txt
data74.txt
data75.txt
data76.txt
data77.txt
data78.txt
data79.txt
data80.txt
data81.txt
data82.txt
data83.txt
data84.txt
data85.txt
data86.txt
data87.txt
data88.txt
data89.txt
data90.txt
data91.txt
data92.txt
data93.txt
data94.txt
data95.txt
data96.txt
data97.txt
data98.txt
data99.txt
data100.txt
data101.txt
data102.txt
data103.txt
data104.txt
data105.txt
data106.txt
data107.txt
data108.txt
data109.txt
data110.txt
data111.txt
data112.txt
data113.txt
data114.txt
data115.txt
data116.txt
data117.txt
data118.txt
data119.txt
data120.txt
data121.txt
data122.txt
data123.txt
data124.txt
data125.txt
data126.txt
data127.txt
data128.txt
data129.txt
data130.txt
data131.txt
data132.txt
data133.txt
data134.txt
data135.txt
data136.txt
data137.txt
data138.txt
data139.txt
data140.txt
data141.txt
data142.txt
data143.txt
data144.txt
data145.txt
data146.txt
data147.txt
data148.txt
data149.txt
data150.txt
data151.txt
data152.txt
data153.txt
data154.txt
data155.txt
data156.txt
data157.txt
data158.txt
data159.txt
data160.txt
data161.txt
data162.txt
data163.txt
data164.txt
data165.txt
data166.txt
data167.txt
data168.txt
data169.txt
data170.txt
data171.txt
data172.txt
data173.txt
data174.txt
data175.txt
data176.txt
data177.txt
data178.txt
data179.txt
data180.txt
data181.txt
data182.txt
data183.txt
data184.txt
data185.txt
data186.txt
data187.txt
data188.txt
data189.txt
data190.txt
data191.txt
data192.txt
data193.txt
data194.txt
data195.txt
data196.txt
data197.txt
data198.txt
data199.txt
data200.txt
data201.txt
data202.txt
data203.txt
data204.txt
data205.txt
data206.txt
data207.txt
data208.txt
data209.txt
data210.txt
data211.txt
data212.txt
data213.txt
data214.txt
data215.txt
data216.txt
data217.txt
data218.txt
data219.txt
data220.txt
data221.txt
data222.txt
data223.txt
data224.txt
data225.txt
data226.txt
data227.txt
data228.txt
data229.txt
data230.txt
data231.txt
data232.txt
data233.txt
data234.txt
data235.txt
data236.txt
data237.txt
data238.txt
data239.txt
data240.txt
data241.txt
data242.txt
data243.txt
data244.txt
data245.txt
data246.txt
data247.txt
data248.txt
data249.txt
data250.txt
data251.txt
data252.txt
data253.txt
data254.txt
data255.txt
data256.txt
data257.txt
data258.txt
data259.txt
data260.txt
data261.txt
data262.txt
data263.txt
data264.txt
data265.txt
data266.txt
data267.txt
data268.txt
data269.txt
data270.txt
data271.txt
data272.txt
data273.txt
data274.txt
data275.txt
data276.txt
data277.txt
data278.txt
data279.txt
data280.txt
data281.txt
data282.txt
data283.txt
data284.txt
data285.txt
data286.txt
data287.txt
data288.txt
data289.txt
data290.txt
data291.txt
data292.txt
data293.txt
data294.txt
data295.txt
data296.txt
data297.txt
data298.txt
data299.txt
data300.txt
data301.txt
data302.txt
data303.txt
data304.txt
data305.txt
data306.txt
data307.txt
data308.txt
data309.txt
data310.txt
data311.txt
data312.txt
data313.txt
data314.txt
data315.txt
data316.txt
data317.txt
data318.txt
data319.txt
data320.txt
data321.txt
data322.txt
data323.txt
data324.txt
data325.txt
data326.txt
data327.txt
data328.txt
data329.txt
data330.txt
data331.txt
data332.txt
data333.txt
data334.txt
data335.txt
data336.txt
data337.txt
data338.txt
data339.txt
data340.txt
data341.txt
data342.txt
data343.txt
data344.txt
data345.txt
data346.txt
data347.txt
data348.txt
data349.txt
data350.txt
data351.txt
data352.txt
data353.txt
data354.txt
data355.txt
data356.txt
data357.txt
data358.txt
data359.txt
data360.txt
data361.txt
data362.txt
data363.txt
data364.txt
data365.txt
data366.txt
data367.txt
data368.txt
data369.txt
data370.txt
data371.txt
data372.txt
data373.txt
data374.txt
data375.txt
data376.txt
data377.txt
data378.txt
data379.txt
data380.txt
data381.txt
data382.txt
data383.txt
data384.txt
data385.txt
data386.txt
data387.txt
data388.txt
data389.txt
data390.txt
data391.txt
data392.txt
data393.txt
data394.txt
data395.txt
data396.txt
data397.txt
data398.txt
data399.txt
data400.txt

In [10]:

# Concatenate all data into one DataFrame
merged_frame = pd.concat(dataFrames,axis=1)
# print merged dataframe
print(merged_frame)

          #    time  covered_sites_spec1  covered_sites_spec2      #    time  \
0      0.01   354.0                340.0                  NaN   0.01   394.0
1      0.02   646.0                644.0                  NaN   0.02   730.0
2      0.03   882.0                886.0                  NaN   0.03   960.0
3      0.04  1080.0               1116.0                  NaN   0.04  1144.0
4      0.05  1266.0               1284.0                  NaN   0.05  1328.0
...     ...     ...                  ...                  ...    ...     ...
1995  19.96  2370.0               2354.0                  NaN  19.96  2354.0
1996  19.97  2360.0               2344.0                  NaN  19.97  2380.0
1997  19.98  2320.0               2342.0                  NaN  19.98  2390.0
1998  19.99  2312.0               2330.0                  NaN  19.99  2410.0
1999  20.00  2308.0               2336.0                  NaN  20.00  2366.0

      covered_sites_spec1  covered_sites_spec2      #    time  ...  \
0                   354.0                  NaN   0.01   368.0  ...
1                   656.0                  NaN   0.02   668.0  ...
2                   922.0                  NaN   0.03   922.0  ...
3                  1124.0                  NaN   0.04  1118.0  ...
4                  1304.0                  NaN   0.05  1290.0  ...
...                   ...                  ...    ...     ...  ...
1995               2312.0                  NaN  19.96  2462.0  ...
1996               2334.0                  NaN  19.97  2464.0  ...
1997               2358.0                  NaN  19.98  2466.0  ...
1998               2360.0                  NaN  19.99  2456.0  ...
1999               2352.0                  NaN  20.00  2482.0  ...

      covered_sites_spec1  covered_sites_spec2      #    time  \
0                   348.0                  NaN   0.01   348.0
1                   634.0                  NaN   0.02   676.0
2                   854.0                  NaN   0.03   898.0
3                  1086.0                  NaN   0.04  1110.0
4                  1272.0                  NaN   0.05  1316.0
...                   ...                  ...    ...     ...
1995               2334.0                  NaN  19.96  2336.0
1996               2336.0                  NaN  19.97  2346.0
1997               2358.0                  NaN  19.98  2340.0
1998               2362.0                  NaN  19.99  2368.0
1999               2356.0                  NaN  20.00  2384.0

      covered_sites_spec1  covered_sites_spec2      #    time  \
0                   348.0                  NaN   0.01   340.0
1                   672.0                  NaN   0.02   664.0
2                   938.0                  NaN   0.03   908.0
3                  1168.0                  NaN   0.04  1116.0
4                  1302.0                  NaN   0.05  1254.0
...                   ...                  ...    ...     ...
1995               2372.0                  NaN  19.96  2386.0
1996               2354.0                  NaN  19.97  2364.0
1997               2340.0                  NaN  19.98  2356.0
1998               2314.0                  NaN  19.99  2344.0
1999               2336.0                  NaN  20.00  2350.0

      covered_sites_spec1  covered_sites_spec2
0                   336.0                  NaN
1                   634.0                  NaN
2                   862.0                  NaN
3                  1046.0                  NaN
4                  1226.0                  NaN
...                   ...                  ...
1995               2344.0                  NaN
1996               2356.0                  NaN
1997               2368.0                  NaN
1998               2370.0                  NaN
1999               2378.0                  NaN

[2000 rows x 1600 columns]

In [11]:
data_spec1 = merged_frame['time'].values

In [12]:
data_spec2 = merged_frame['covered_sites_spec1'].values

In [13]:
data_spec1

array([[ 354.,  394.,  368., ...,  348.,  348.,  340.],
       [ 646.,  730.,  668., ...,  646.,  676.,  664.],
       [ 882.,  960.,  922., ...,  900.,  898.,  908.],
       ...,
       [2320., 2390., 2466., ..., 2286., 2340., 2356.],
       [2312., 2410., 2456., ..., 2334., 2368., 2344.],
       [2308., 2366., 2482., ..., 2350., 2384., 2350.]])

In [14]:
data_spec2

array([[ 340.,  354.,  406., ...,  348.,  348.,  336.],
       [ 644.,  656.,  724., ...,  634.,  672.,  634.],
       [ 886.,  922.,  934., ...,  854.,  938.,  862.],
       ...,
       [2342., 2358., 2340., ..., 2358., 2340., 2368.],
       [2330., 2360., 2358., ..., 2362., 2314., 2370.],
       [2336., 2352., 2360., ..., 2356., 2336., 2378.]])

In [15]:
np.savetxt('KMC_spec1.txt', data_spec1, fmt='%d')

In [16]:
np.savetxt('KMC_spec2.txt', data_spec2, fmt='%d')